version: 2
jobs:
  build:
    working_directory: ~/code
    environment:
      CC_TEST_REPORTER_ID: cf0482a47e3601e1eec2e11f822ec0967e35fbee74c0df4f81dba1a24fa02019
      JVM_OPTS: -Xmx3200m
    docker:
      - image: circleci/android:api-29-node
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Install licenses
          command: cp licenses/* /opt/android/sdk/licenses/
      - run:
          name: Approve license for build tools
          command: (echo y; echo y; echo y; echo y; echo y; echo y) | $ANDROID_HOME/tools/bin/sdkmanager --licenses && sdkmanager --update
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Running Unit Tests
          command: |
            ./gradlew testStagingDebugUnitTest
      - run:
          name: Lint prod debug
          command: |
            ./gradlew clean :app:lintProdDebug
      - run:
          name: Ktlint checks
          command: |
            ./gradlew ktlint
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
            ./cc-test-reporter after-build
