version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Unit Tests
          command: ./gradlew testStagingDebugUnitTest
      - run:
          name: Run Ktlint
          command: ./gradlew ktlint
      # todo add instrumentation test
      - run:
          name: Setup emulator
          command: (yes | sdkmanager "system-images;android-29;default;x86_64" && echo "no" | avdmanager create avd -n test -k "system-images;android-29;default;x86_64") || true
      - run:
          name: open emulator
          command: emulator -avd test -no-audio &
      - run:
          name: Run EspressoTests
          command: ./gradlew connectedStagingDebugAndroidTest
